### Requisição para a raiz da aplicação 
GET http://localhost:5247/api/produto/listar


### Requisição para a segunda raiz
GET  http://localhost:5247 

GET  http://localhost:5247//api/produto/cadastrar/{nome}